version: "3.9" # optional since v1.27.0
services:
  activity-backend:
    container_name: activity-backend
    build: ./activity-backend
    volumes:
      - "./activity-backend:/usr/src/activity-backend"
      - "/usr/src/activity-backend/node_modules"
    ports:
      - 5000:5000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command:
      [
        "/usr/src/activity-backend/wait-for-it.sh",
        "cassandra:9042",
        "--",
        "npm",
        "start",
      ]
    depends_on:
      - cassandra
  feed-backend:
    container_name: feed-backend
    build: ./feed-backend
    volumes:
      - "./feed-backend:/usr/src/feed-backend"
      - "/usr/src/feed-backend/node_modules"
    ports:
      - 5008:5008
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    depends_on:
      - redis
  feed-web:
    container_name: feed-web
    build: ./feed-web
    volumes:
      - "./feed-web:/usr/src/feed-web"
      - "/usr/src/feed-web/node_modules"
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn start
    depends_on:
      - feed-backend

  redis:
    image: redis
  cassandra:
    image: cassandra
    ports:
      - 9042:9042
