version: "3.9" # optional since v1.27.0
services:
  feed-backend:
    container_name: feed-backend
    build: ./feed-backend
    volumes:
      - "./:/feed-backend"
      - "/feed-backend/node_modules"
    ports:
      - 5008:5008
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    depends_on:
      - redis
  feed-web:
    container_name: feed-web
    build: ./feed-web
    volumes:
      - "./:/feed-web"
      - "/feed-web/node_modules"
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn start
    depends_on:
      - feed-backend
  redis:
    image: redis
