version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    command: npm start
    ports:
      - "5008:5008"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - redis
  redis:
    image: redis